### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by war100ck** [PsykoDev/Qol-Pack#2]
`[18:35:39.737] [mods] ERROR: Module "Qol-Pack" (Qol-Pack) could not be loaded!
[18:35:39.738] [mods] ERROR: Please contact the module's author: https://github.com/PsykoDev/Qol-Pack/issues
[18:35:39.744] ReferenceError: lastTimeMoved is not defined
    at new QolPack (F:\from games\TeraToolbox1\mods\Qol-Pack-master\index.js:10:21)
    at ModuleManager.load (F:\from games\TeraToolbox1\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at F:\from games\TeraToolbox1\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (F:\from games\TeraToolbox1\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (F:\from games\TeraToolbox1\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:215:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1114:10)`

**Comment by N-Kata** [comment]
let lastTimeMoved = Date.now();
  let interval = config.interval,
      throttleMax = config.throttleMax,
      scanInterval = config.scanInterval,
      radius = config.radius;

      let npcs = new Set();

      let characters = []
      let position = -1

  let location = null,
      items = new Map(),
      lootTimeout = null;
 
      let w,
          loc,
          dest,
          job,
          templateId;

      let gameId = -0n,
          outOfEnergy = false,
          dismountByUser = false,
          mountDisabled = false,
          inCombat = false,
          mountSkill = -1,
          serverMounted = false,
          remountTimer = null,
          unlock = false

change similar lines in index.js to this
